services:
  oryx:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/oryx:v5.15.20
    container_name: netops-oryx
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    ports:
      - "80:2022"
      - "443:2443"
      - "1935:1935"
      - "8000:8000/udp"
      - "10080:10080/udp"
