apiVersion: 1

datasources:
  - name: InfluxDB-NetOps
    type: influxdb
    access: proxy
    url: http://netops-influxdb:8086
    database: netops
    user: admin
    secureJsonData:
      password: admin123
    isDefault: true
    editable: true
