apiVersion: 1

datasources:
  - name: Zabbix-NetOps
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://netops-zabbix-web:8080/api_jsonrpc.php
    isDefault: false
    editable: true
    jsonData:
      username: Admin
      trends: true
      trendsFrom: "7d"
      cacheTTL: "1h"
    secureJsonData:
      password: zabbix
