module(load="imudp")
input(type="imudp" port="514" ruleset="netops_network")

module(load="imtcp")
input(type="imtcp" port="514" ruleset="netops_network")

template(name="NetopsNetworkFormat" type="string"
         string="%timegenerated% %fromhost-ip% %hostname% %syslogtag%%msg%\n")

template(name="NetopsNetworkFileByIP" type="string"
         string="/opt/netops-box/logs/syslog/%fromhost-ip%.log")

ruleset(name="netops_network") {
    action(
        type="omfile"
        dynaFile="NetopsNetworkFileByIP"
        template="NetopsNetworkFormat"
        createDirs="on"
    )
}

