[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "1s"
  hostname = "monitor"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "netops"
  timeout = "5s"
###############################################################################
# Ping - 网络设备
###############################################################################

# 核心交换机
[[inputs.ping]]
  urls = ["192.168.10.254"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  ipv6 = false

  [inputs.ping.tags]
    node_group = "network_device"
    node_group_name = "网络设备"
    node_name = "核心交换机-C9300"
    node_ip = "192.168.10.254"
    node_role = "core-switch"

# 防火墙网关
[[inputs.ping]]
  urls = ["192.168.19.253"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  ipv6 = false

  [inputs.ping.tags]
    node_group = "network_device"
    node_group_name = "网络设备"
    node_name = "防火墙网关"
    node_ip = "192.168.19.253"
    node_role = "firewall-gateway"

# 监控服务器，也可以先放到网络设备里
[[inputs.ping]]
  urls = ["192.168.199.200"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  ipv6 = false

  [inputs.ping.tags]
    node_group = "network_device"
    node_group_name = "网络设备"
    node_name = "监控服务器"
    node_ip = "192.168.199.200"
    node_role = "monitor-server"



###############################################################################
# Ping - 外网网关
###############################################################################

# 114 DNS
[[inputs.ping]]
  urls = ["114.114.114.114"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  ipv6 = false

  [inputs.ping.tags]
    node_group = "internet_gateway"
    node_group_name = "外网网关"
    node_name = "外网DNS-114"
    node_ip = "114.114.114.114"
    node_role = "public-dns"

# 阿里 DNS
[[inputs.ping]]
  urls = ["223.5.5.5"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  ipv6 = false

  [inputs.ping.tags]
    node_group = "internet_gateway"
    node_group_name = "外网网关"
    node_name = "外网DNS-阿里"
    node_ip = "223.5.5.5"
    node_role = "public-dns"

###############################################################################
# Ping - 网络大包
###############################################################################

# AC控制器
[[inputs.ping]]
  urls = ["192.168.197.200"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  deadline = 2
  size = 1500
  ipv6 = false

  [inputs.ping.tags]
    node_group = "network_device"
    node_group_name = "网络大包"
    node_name = "AC控制器"
    node_ip = "192.168.197.200"
